"""empty message

Revision ID: 1d57831fc5da
Revises: 399e090ef5e8
Create Date: 2014-10-12 12:52:31.979148

"""

# revision identifiers, used by Alembic.
revision = '1d57831fc5da'
down_revision = '399e090ef5e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
