"""empty message

Revision ID: 2027216f866d
Revises: None
Create Date: 2014-10-29 11:38:53.317478

"""

# revision identifiers, used by Alembic.
revision = '2027216f866d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
