"""empty message

Revision ID: 260bae85527a
Revises: None
Create Date: 2014-10-06 12:15:32.494328

"""

# revision identifiers, used by Alembic.
revision = '260bae85527a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
