"""empty message

Revision ID: 2b8f052f9932
Revises: 3f974ba313bf
Create Date: 2014-10-08 20:10:12.616982

"""

# revision identifiers, used by Alembic.
revision = '2b8f052f9932'
down_revision = '3f974ba313bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
