"""empty message

Revision ID: 2f0f0d645c93
Revises: None
Create Date: 2014-10-04 21:32:17.702693

"""

# revision identifiers, used by Alembic.
revision = '2f0f0d645c93'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
