"""empty message

Revision ID: 3387dc146145
Revises: 4419228d4d48
Create Date: 2014-10-12 16:23:00.523164

"""

# revision identifiers, used by Alembic.
revision = '3387dc146145'
down_revision = '4419228d4d48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
