"""empty message

Revision ID: 36f3105def42
Revises: 1f177797ad29
Create Date: 2014-10-08 22:20:57.523601

"""

# revision identifiers, used by Alembic.
revision = '36f3105def42'
down_revision = '1f177797ad29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
