"""empty message

Revision ID: 399e090ef5e8
Revises: 41b7c0268ce5
Create Date: 2014-10-11 23:16:00.578884

"""

# revision identifiers, used by Alembic.
revision = '399e090ef5e8'
down_revision = '41b7c0268ce5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
