"""empty message

Revision ID: 3a29b817633c
Revises: 3b2f28edc7d0
Create Date: 2014-10-05 23:06:15.747111

"""

# revision identifiers, used by Alembic.
revision = '3a29b817633c'
down_revision = '3b2f28edc7d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
