"""empty message

Revision ID: 3a6871975706
Revises: 7b4793d4ab3
Create Date: 2014-10-27 15:13:39.829936

"""

# revision identifiers, used by Alembic.
revision = '3a6871975706'
down_revision = '7b4793d4ab3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
