"""empty message

Revision ID: 3b2f28edc7d0
Revises: 59e202b03f2c
Create Date: 2014-10-05 21:12:03.821678

"""

# revision identifiers, used by Alembic.
revision = '3b2f28edc7d0'
down_revision = '59e202b03f2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
