"""empty message

Revision ID: 3f974ba313bf
Revises: 260bae85527a
Create Date: 2014-10-08 11:01:05.360359

"""

# revision identifiers, used by Alembic.
revision = '3f974ba313bf'
down_revision = '260bae85527a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
