"""empty message

Revision ID: 41b7c0268ce5
Revises: 36f3105def42
Create Date: 2014-10-11 23:12:15.743830

"""

# revision identifiers, used by Alembic.
revision = '41b7c0268ce5'
down_revision = '36f3105def42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
