"""empty message

Revision ID: 4302455b22d
Revises: 3387dc146145
Create Date: 2014-10-12 21:45:27.519869

"""

# revision identifiers, used by Alembic.
revision = '4302455b22d'
down_revision = '3387dc146145'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
