"""empty message

Revision ID: 4419228d4d48
Revises: 165fbfaa9a9a
Create Date: 2014-10-12 14:23:42.591502

"""

# revision identifiers, used by Alembic.
revision = '4419228d4d48'
down_revision = '165fbfaa9a9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
