"""empty message

Revision ID: 47b246ee0271
Revises: 2f0f0d645c93
Create Date: 2014-10-04 21:33:34.214759

"""

# revision identifiers, used by Alembic.
revision = '47b246ee0271'
down_revision = '2f0f0d645c93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
