"""empty message

Revision ID: 48147c019f38
Revises: 2b8f052f9932
Create Date: 2014-10-08 21:35:30.585712

"""

# revision identifiers, used by Alembic.
revision = '48147c019f38'
down_revision = '2b8f052f9932'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    ### end Alembic commands ###
