"""empty message

Revision ID: 4b22e1420478
Revises: 3a6871975706
Create Date: 2014-10-27 18:16:42.683063

"""

# revision identifiers, used by Alembic.
revision = '4b22e1420478'
down_revision = '3a6871975706'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
