"""empty message

Revision ID: 4f796700409b
Revises: 1d57831fc5da
Create Date: 2014-10-12 13:36:14.693422

"""

# revision identifiers, used by Alembic.
revision = '4f796700409b'
down_revision = '1d57831fc5da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bestfriend')
    op.add_column('friends', sa.Column('friend_accunt', sa.Integer(), nullable=True))
    op.drop_column('friends', 'added_by')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('friends', 'friend_accunt')
    op.create_table('bestfriend',
    sa.Column('id', sa.INTEGER(), server_default="nextval('bestfriend_id_seq'::regclass)", nullable=False),
    sa.Column('best_friend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], [u'friends.id'], name=u'bestfriend_friend_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'bestfriend_pkey')
    )
    ### end Alembic commands ###
