"""empty message

Revision ID: 5543e1236be4
Revises: 2027216f866d
Create Date: 2014-11-08 22:37:45.242098

"""

# revision identifiers, used by Alembic.
revision = '5543e1236be4'
down_revision = '2027216f866d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
