"""empty message

Revision ID: 59e202b03f2c
Revises: None
Create Date: 2014-10-05 12:53:44.333640

"""

# revision identifiers, used by Alembic.
revision = '59e202b03f2c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
