"""empty message

Revision ID: 7b4793d4ab3
Revises: b6c789a2ab6
Create Date: 2014-10-14 11:04:14.574984

"""

# revision identifiers, used by Alembic.
revision = '7b4793d4ab3'
down_revision = 'b6c789a2ab6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
