"""empty message

Revision ID: a44ac079527
Revises: 5543e1236be4
Create Date: 2014-11-08 23:04:31.881591

"""

# revision identifiers, used by Alembic.
revision = 'a44ac079527'
down_revision = '5543e1236be4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
