"""empty message

Revision ID: b6c789a2ab6
Revises: c3b2317cd3b
Create Date: 2014-10-13 19:44:40.722162

"""

# revision identifiers, used by Alembic.
revision = 'b6c789a2ab6'
down_revision = 'c3b2317cd3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friend_tag', ['friend_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend_tag')
    ### end Alembic commands ###
